### ISSUE TITLE
Class Calculator implementing ICalculator

### ISSUE THREAD

**Issue by franciscoSevilla** [franciscoSevilla/Repo_Java_Training#2]
https://github.com/franciscoSevilla/Repo_Java_Training/blob/7991e7cad1ae43b585a2649f73bc8af02523d7a2/HelloWordMavenDockerized/src/main/java/com/privalia/business/Calculator.java#L1-L33

**Comment by jordiascension** [comment]
If it's in done column then it should be closed.
